const routes=[
['МРС → Ольхон','Пересечь Байкал и отправиться навстречу острову Ольхон.','5–6 часов','assets/baikal-hero.webp'],
['МРС → Огой','Остров Огой, байкальский лёд и знаменитая Ступа Просветления.','3–4 часа','assets/baikal-ogoy.webp'],
['МРС → Хужир','Путешествие к сердцу Ольхона и легендарной скале Шаманка.','3–4 часа','assets/baikal-shamanka.webp'],
['Хужир → Хобой','Север Ольхона, бескрайний Байкал и виды на скалы, впечатляющие своей историей.','6–8 часов','assets/baikal-khoboy.webp'],
['Хужир → Саган-Хушун','Белоснежные скалы, прозрачный лёд и северное побережье Ольхона.','3–4 часа','assets/baikal-grotto.webp'],
['МРС → Малое Море','Панорамные путешествия среди островов, бухт и скал Малого Моря.','3–4 часа','assets/baikal-coast.webp'],
['Индивидуальный маршрут','Соберите собственное путешествие по Байкалу.','По запросу','assets/baikal-sunset.webp']];
function cropMarkup(src,alt=''){return `<div class="crop" data-image="${src}" role="img" aria-label="${alt}"></div>`}
function fillCrops(root=document){root.querySelectorAll('[data-image]').forEach(el=>{if(el.firstElementChild)return;const im=document.createElement('img');im.src=el.dataset.image;im.alt='';im.loading=el.classList.contains('hero-photo')?'eager':'lazy';im.decoding='async';el.append(im)})}
const grid=document.querySelector('#route-grid');
routes.forEach((r,i)=>{const article=document.createElement('article');article.className='route';article.innerHTML=`<a href="#route-${i}" data-route="${i}" aria-label="Подробнее: ${r[0]}">${cropMarkup(r[3],r[0])}<h3>${r[0]}</h3><p>${r[1]}</p><div class="route-bottom"><span>◷ ${r[2]}</span><span class="round-link" aria-hidden="true">→</span></div></a>`;grid.append(article)});
grid.insertAdjacentHTML('beforeend','<aside class="route-note"><span>⌖</span><p>Доступность маршрутов зависит от сезона, погодных условий, ледовой обстановки и действующих правил проведения поездок.</p></aside>');
const photos=[['assets/baikal-hero.webp','Прозрачный байкальский лёд'],['assets/baikal-coast.webp','Хивус на Байкале'],['assets/baikal-grotto.webp','Ледяные гроты'],['assets/baikal-bubbles.webp','Пузырьки во льду'],['assets/baikal-sunset.webp','Закат на Байкале'],['assets/baikal-khoboy.webp','Зимние горы'],['assets/baikal-shamanka.webp','На берегу Байкала']];
const gallery=document.querySelector('#gallery-track');photos.forEach((p,i)=>{gallery.insertAdjacentHTML('beforeend',`<button data-photo="${i}" aria-label="Открыть фото: ${p[1]}">${cropMarkup(p[0],p[1])}</button>`)});
function wireBookings(root=document){root.querySelectorAll('[data-book]').forEach(a=>{const message=a.dataset.book||'Здравствуйте! Хочу забронировать поездку на хивусе по Байкалу. Подскажите доступные даты и маршруты.';a.href='https://t.me/MariaPM65?text='+encodeURIComponent(message);a.target='_blank';a.rel='noopener noreferrer'})}
fillCrops();wireBookings();
const dialog=document.querySelector('#detail'),content=document.querySelector('#detail-content');
function openDialog(html){content.innerHTML=html;fillCrops(content);wireBookings(content);dialog.showModal();document.body.classList.add('modal-open')}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();const route=routes[Number(r.dataset.route)];openDialog(`${cropMarkup(route[3],route[0])}<h2>${route[0]}</h2><p>${route[1]}</p><p>Ориентировочная продолжительность: ${route[2]}. Точки остановок, условия и стоимость уточняются при бронировании. Возможность поездки зависит от погоды и ледовой обстановки.</p><a class="button" data-book="Здравствуйте! Интересует маршрут ${route[0]}. Подскажите стоимость и доступные даты.">Обсудить маршрут в Telegram ↗</a>`)}const p=e.target.closest('[data-photo]');if(p){const photo=photos[Number(p.dataset.photo)];openDialog(`${cropMarkup(photo[0],photo[1])}<h2>${photo[1]}</h2>`)}});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
document.querySelectorAll('[data-gallery-step]').forEach(b=>b.addEventListener('click',()=>gallery.scrollBy({left:Number(b.dataset.galleryStep)*gallery.clientWidth*.65,behavior:'smooth'})));
let selected=-1;document.querySelectorAll('[data-route-step]').forEach(b=>b.addEventListener('click',()=>{selected=(selected+Number(b.dataset.routeStep)+routes.length)%routes.length;grid.querySelectorAll('.route').forEach((card,i)=>card.classList.toggle('selected',i===selected));const card=grid.children[selected];card.querySelector('a').focus({preventScroll:true});card.scrollIntoView({behavior:'smooth',block:'nearest'})}));
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.header nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
